version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio del Backend FastAPI
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Sincroniza el código local con el contenedor
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PROJECT_NAME='Inventory Management API'
      - ENV=development
      - DEBUG=True
      - DATABASE_URL='postgresql+asyncpg://postgres:postgrespassword@db:5432/inventory_db'
      - SECRET_KEY='8f9b23e1d4c7a6b5e4f3d2c1b0a9f8e7d6c5b4a3'
      - ALGORITHM='HS256'
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db

volumes:
  postgres_data: